import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Container from '../components/Container';
import AccountSidebar from '../components/account/AccountSidebar';
import { useAuth } from '../context/AuthContext';
import { MY_LAB_TESTS } from '../data/labTestDetailData';
import { FlaskConical, ChevronRight, Download, FileText } from 'lucide-react';

const statusStyle = {
  Completed:     'bg-blue-100 text-[var(--color-primary)]',
  'Report Ready': 'bg-green-100 text-[var(--color-success)]',
  Processing:    'bg-orange-100 text-orange-500',
};

const downloadableStatuses = ['Completed', 'Report Ready'];

function handleDownload(e, test) {
  e.stopPropagation();
  // Create a mock text content simulating a PDF report
  const content = [
    `MEDIHUB - LAB TEST REPORT`,
    `================================`,
    `Test Name   : ${test.name}`,
    `Order ID    : #${test.orderId}`,
    `Test Date   : ${test.date}`,
    `Includes    : ${test.includes}`,
    `Amount Paid : ₹${test.price}`,
    `Status      : ${test.status}`,
    `================================`,
    `Report generated by MediHub`,
    `For queries: support@medihub.com`,
  ].join('\n');

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `MediHub_Report_${test.orderId}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function MyLabTests() {
  const { user, setShowLogin } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    if (!user) { setShowLogin(true); navigate('/'); }
  }, [user]);

  if (!user) return null;

  return (
    <div className="min-h-screen bg-[var(--color-bg-main)]">
      <Navbar />
      <Container className="py-8">
        <div className="flex gap-7 items-start">
          <div className="hidden lg:block w-64 shrink-0">
            <AccountSidebar active="labtests" onChange={() => {}} />
          </div>
          <div className="flex-1 min-w-0 space-y-5">
            <div>
              <h1 className="text-2xl font-bold text-[var(--color-text-dark)]">
                My Lab Tests
              </h1>
              <p className="text-sm text-[var(--color-text-secondary)] mt-1">
                View and manage your booked lab tests
              </p>
            </div>
            <div className="space-y-4">
              {MY_LAB_TESTS.map((test) => (
                <div
                  key={test.id}
                  onClick={() => navigate(`/lab-test/${test.id}`)}
                  className="bg-white rounded-2xl border border-[var(--color-border)] hover:border-blue-200 hover:shadow-md transition-all p-5 cursor-pointer"
                >
                  <div className="flex items-center gap-4 flex-wrap md:flex-nowrap">
                    <div className="w-12 h-12 bg-blue-50 rounded-xl flex items-center justify-center shrink-0">
                      <FlaskConical className="w-6 h-6 text-[var(--color-primary)]" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="font-bold text-[var(--color-text-dark)]">
                        {test.name}
                      </p>
                      <p className="text-xs text-[var(--color-text-secondary)]">
                        Order #{test.orderId} • {test.date}
                      </p>
                      <p className="text-xs text-[var(--color-text-secondary)]">
                        Includes {test.includes}
                      </p>
                    </div>
                    <div className="flex flex-col md:flex-row items-center gap-3 shrink-0">
                      <div className="text-right">
                        <p className="font-bold text-[var(--color-text-dark)] mb-1">
                          ₹{test.price}
                        </p>
                        <span
                          className={`text-xs font-semibold px-2.5 py-1 rounded-full ${statusStyle[test.status] || "bg-gray-200 text-gray-600"}`}
                        >
                          {test.status}
                        </span>
                      </div>

                      <div className="flex items-center gap-2 text-right">
                        {downloadableStatuses.includes(test.status) && (
                          <button
                            onClick={(e) => handleDownload(e, test)}
                            title="Download Report"
                            className="flex items-center justify-end gap-1.5 border cursor-pointer border-[var(--color-success)] text-[var(--color-success)] hover:bg-green-50 text-xs font-semibold px-3 py-2 rounded-xl transition-all shrink-0"
                          >
                            <Download className="w-3.5 h-3.5" />
                            <span className="hidden sm:inline">Download</span>
                          </button>
                        )}

                        <ChevronRight className="w-7 h-7 text-[var(--color-text-secondary)] bg-blue-100 rounded-[5px] shrink-0" />
                      </div>
                      {/* Download button — only for completed/report ready */}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </Container>
      <Footer />
    </div>
  );
}
